Client/urls.py
from django.conf.urls import url
from Client.views import *

app_name = 'Client'

urlpatterns = [
    url(r'^profile/(?P<profile_client>[\w-]+)/$', ProfileClient.as_view(), name='ProfileClient'),
    url(r'^login$', LoginClient.as_view(), name='LoginClient'),
    url(r'^register', RegisterClient.as_view(), name='RegisterClient'),
    url(r'^logout_user/(?P<session_user>[\w-]+)/$', LogoutClient.as_view(), name='logoutClient'),
    url(r'^authentication/$', CheckLoginClient.as_view(), name='Login_Form_Ajax'),
    url(r'^settings/(?P<profile_client>[\w-]+)/$', SettingsClient.as_view(), name='SettingsClient'),
    url(r'^check_verify_code/$', CheckVerifyCode.as_view(), name='Check_Verify_Code_Ajax'),
    url(r'^save_settings/$', SaveSettings.as_view(), name='Save_Settings_Ajax'),
    url(r'^change_password/$', ChangePassword.as_view(), name='Change_Password_Ajax'),
    url(r'^change_email/$', ChangeEmail.as_view(), name='Change_Email_Ajax'),
    url(r'^verify_password/$', VerifyPassword.as_view(), name='VerifyPasswordAjax'),
    url(r'^create_account/$', CreateAccount.as_view(), name='CreateAccountAjax'),
]

Exam/urls.py
from django.conf.urls import url
from Exam.views import *

app_name = 'Exam'

urlpatterns = [
    url(r'^$', ViewExams.as_view(), name='ViewExams'),
    url(r'^add/$', AddExam.as_view(), name='Add_Exam'),
    # url(r'^edit/$', EditExam.as_view(), name='Edit_Exam_Ajax'),
    # url(r'^remove/$', RemoveExam.as_view(), name='Remove_Exam_Ajax'),
]

PalestineHistory/urls.py
from django.conf.urls import url, include
from Questions.views import *
from django.conf import settings
from django.conf.urls.static import static
from Client.views import *
from django.contrib import admin

urlpatterns = [
    # WebSite
    url(r'^$', MainPage.as_view(), name='MainPage'),

    # Dashboard
    url(r'^dashboard/admin_django/', admin.site.urls),
    url(r'^dashboard/', include('Dashboard.urls'), name='Dashboard'),

    # Client
    url(r'^user/', include('Client.urls'), name='Client'),

    # Client
    url(r'^user/', include('Video.urls'), name='Viedo'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Client/models.py
from django.db import models
from Category.models import Category


# Create your models here.
class Manager(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
    is_active = models.BooleanField(default=True)
    is_manager = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id) + " || " + str(self.username)


class Client(models.Model):
    email = models.CharField(max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=30)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    father_name = models.CharField(max_length=30)
    grand_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    mobile = models.CharField(max_length=30)
    gender = models.CharField(max_length=4)
    is_active = models.BooleanField(default=False)
    identity = models.CharField(max_length=15)

    def __str__(self):
        return str(self.id)


class UserAgents(models.Model):
    ip = models.CharField(max_length=25, null=True, blank=True)
    user = models.CharField(max_length=60)
    browser_family = models.CharField(max_length=30, null=True, blank=True)
    browser_version = models.CharField(max_length=15, null=True, blank=True)
    os_family = models.CharField(max_length=30, null=True, blank=True)
    os_version = models.CharField(max_length=15, null=True, blank=True)
    device_family = models.CharField(max_length=30, null=True, blank=True)
    start_session = models.DateTimeField(auto_now=False, auto_now_add=True)
    end_session = models.DateTimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    logout = models.BooleanField(default=False)
    manage = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id) + " || " + str(self.user)


class LoginAttempts(models.Model):
    ip = models.CharField(max_length=25, null=True, blank=True)
    name = models.CharField(max_length=40, null=True, blank=True)
    password = models.CharField(max_length=40, null=True, blank=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)
    browser_family = models.CharField(max_length=30, null=True, blank=True)
    browser_version = models.CharField(max_length=15, null=True, blank=True)
    os_family = models.CharField(max_length=30, null=True, blank=True)
    os_version = models.CharField(max_length=15, null=True, blank=True)
    device_family = models.CharField(max_length=30, null=True, blank=True)
    manage = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id) + " || " + str(self.name)


class VerifyEmail(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now=False, auto_now_add=True)
    random_number = models.CharField(max_length=10, null=True, blank=True)

Client/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import *
from django.http import JsonResponse
from django.views.generic import View
from ipware.ip import get_real_ip
from django.utils import timezone
from django.contrib.auth.views import logout
from django.core.urlresolvers import reverse
from Category.models import Category
import re, datetime
from django.db.models import Q
from django.template import loader
from django.core.mail import send_mail
from django.utils.crypto import get_random_string
from Event.models import Event
from Video.models import Video


class ViewUsers(View):
    def get(self, request):
        if request.session.get('manage', None):
            session_user = request.session.get('manage', None)
            user_agent_oop = UserAgents.objects.filter(user=session_user).latest('id')
            if not user_agent_oop.logout:
                all_client = Client.objects.all()
                all_category = Category.objects.all()
                context = {
                    'title': 'عرض المستخدمين',
                    'all_client': all_client,
                    'logout_user': session_user,
                    'admin_is_manager': request.session.get('is_manager', False),
                    'session_user': session_user.split('_')[0],
                    'all_category': all_category,
                }
                return render(request, 'Dashboard/Users/view_users.html', context)
        return HttpResponseRedirect(reverse('Dashboard:login'))


class AddUser(View):
    def get(self, request):
        if request.session.get('manage', None):
            session_user = request.session.get('manage', None)
            user_agent_oop = UserAgents.objects.filter(user=session_user).latest('id')
            if not user_agent_oop.logout:
                context = {
                    'title': 'أضف مستخدم جديد',
                    'logout_user': session_user,
                    'admin_is_manager': request.session.get('is_manager', False),
                    'session_user': session_user.split('_')[0],
                }
                return render(request, 'Dashboard/Users/add_user.html', context)
        return HttpResponseRedirect(reverse('Dashboard:login'))


class RemoveUser(View):
    def post(self, request):
        if request.session.get('manage', None):
            session_user = request.session.get('manage', None)
            user_agent_oop = UserAgents.objects.filter(user=session_user).latest('id')
            if not user_agent_oop.logout:
                user_id = request.POST.get("id_user_model", False)
                if user_id:
                    client_oop = Client.objects.filter(pk=user_id)
                    if not client_oop.first():
                        message = "NotExists"
                    else:
                        client_oop.delete()
                        client_oop = Client.objects.filter(pk=user_id)
                        if not client_oop.first():
                            message = 'Done'
                        else:
                            message = 'Fail'
                else:
                    message = "Empty"
                return JsonResponse({'status': message})
            logout(request)
        return HttpResponseRedirect(reverse('Dashboard:login'))


class EditUser(View):
    def post(self, request):
        if request.session.get('manage', None):
            session_user = request.session.get('manage', None)
            user_agent_oop = UserAgents.objects.filter(user=session_user).latest('id')
            if not user_agent_oop.logout:
                user_id = request.POST.get("id_user_model", False)
                if user_id:
                    client_oop = Client.objects.filter(pk=user_id)
                    if not client_oop.first():
                        return JsonResponse({'status': "NotExists"})
                    else:
                        name1 = request.POST.get("name1_user_model", False)
                        name2 = request.POST.get("name2_user_model", False)
                        name3 = request.POST.get("name3_user_model", False)
                        name4 = request.POST.get("name4_user_model", False)
                        email = request.POST.get("email_user_model", False)
                        password = request.POST.get("password_user_model", False)
                        gender = request.POST.get("gender_user_model", False)
                        category = request.POST.get("category_user_model", False)
                        phone = request.POST.get("mobile_user_model", False)
                        identity = request.POST.get("identity_user_model", False)
                        is_active = request.POST.get("is_active_user_model", False)
                        inputs = [name1, name2, name3, name4, email, password, is_active, category, phone, identity]
                        if check_input_is_empty(inputs):
                            return JsonResponse({'msg': 'isEmpty'})
                        else:
                            if not verify_password(password):
                                return JsonResponse({'msg': 'PasswordContextError'})
                            if not verify_email(email):
                                return JsonResponse({'msg': 'EmailContextError'})
                            if gender != "1" and gender != "2":
                                return JsonResponse({'msg': 'GenderContextError'})
                            if is_active != "1" and is_active != "2":
                                return JsonResponse({'msg': 'ActiveContextError'})
                            if not phone.isnumeric() or len(phone) != 10:
                                return JsonResponse({'msg': 'PhoneContextError'})
                            if not identity.isnumeric() or len(identity) != 9:
                                return JsonResponse({'msg': 'IdentityContextError'})
                            if not check_input_is_alpha([name1, name2, name2, name4]):
                                return JsonResponse({'msg': 'NameContextError'})
                            category_oop = Category.objects.filter(identity=category).first()
                            if not category_oop:
                                return JsonResponse({'msg': 'CategoryContextError'})
                            if is_active == "1":
                                active = True
                            else:
                                active = False
                            client_oop.update(email=email, password=password, category=category_oop, first_name=name1,
                                              father_name=name2, grand_name=name3, last_name=name4, gender=gender,
                                              mobile=phone, identity=identity, is_active=active)
                            check_oop = Client.objects.filter(pk=user_id, category=category_oop, email=email,
                                                              password=password, first_name=name1, father_name=name2,
                                                              grand_name=name3, last_name=name4, gender=gender,
                                                              mobile=phone, identity=identity, is_active=active).first()
                            if check_oop:
                                return JsonResponse({'msg': 'Done'})
                            else:
                                return JsonResponse({'msg': 'Fail'})
                else:
                    return JsonResponse({'status': "isEmpty"})
            logout(request)
        return HttpResponseRedirect(reverse('Dashboard:login'))


class MainPage(View):
    def get(self, request):
        videos = Video.objects.all()
        context = {
            'title': 'الصفحة الرئيسية',
            'videos': videos
        }
        if request.session.get('client', False):
            session_user = request.session.get('client', None)
            user_agent_oop = UserAgents.objects.filter(user=session_user).latest('id')
            if not user_agent_oop.logout:
                client_oop = Client.objects.filter(username=session_user).first()
                context['client'] = client_oop
                context['type_session'] = 'Client'
                context['session_user'] = session_user
                context['logout_user'] = session_user
            else:
                logout(request)
        elif request.session.get('manage', None):
            session_user = request.session.get('manage', None)
            user_agent_oop = UserAgents.objects.filter(user=session_user).latest('id')
            if not user_agent_oop.logout:
                context['type_session'] = 'Manager'
                context['session_user'] = session_user.split('_')[0]
                context['logout_user'] = session_user
                context['admin_is_manager'] = request.session.get('is_manager', None)
            else:
                logout(request)
        return render(request, 'main_page.html', context)


class LoginClient(View):
    def get(self, request):
        if request.session.get('manage', None):
            return HttpResponseRedirect(reverse('MainPage'))
        if request.session.get('client', None):
            session_user = request.session.get('client', None)
            user_agent_oop = UserAgents.objects.filter(user=session_user).latest('id')
            if not user_agent_oop.logout:
                return HttpResponseRedirect(reverse('Client:ProfileClient', args={session_user}))
        context = {"title": "تسجيل الدخول"}
        return render(request, 'Client/login.html', context)


class RegisterClient(View):
    def get(self, request):

templates/Client/login.html
{% load staticfiles %}
<html>
<head>
    <title> {{ title }} </title>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <link rel="icon" href="{% static 'image/Male_User.ico' %}">
    <style>
        @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700);

        body {
            background: #456;
            font-family: 'Open Sans', sans-serif;
        }

        .login {
            width: 400px;
            margin: 16px auto;
            font-size: 16px;
        }

        .login-header,
        .login p {
            margin-top: 0;
            margin-bottom: 0;
        }

        .login-triangle {
            width: 0;
            margin-right: auto;
            margin-left: auto;
            border: 12px solid transparent;
            border-bottom-color: #28d;
        }

        .login-header {
            background: #28d;
            padding: 20px;
            font-size: 1.4em;
            font-weight: normal;
            text-align: center;
            text-transform: uppercase;
            color: #fff;
        }

        .login-container {
            background: #ebebeb;
            padding: 12px;
        }

        .login p {
            padding: 12px;
        }

        .login input {
            box-sizing: border-box;
            display: block;
            width: 100%;
            border-width: 1px;
            border-style: solid;
            padding: 16px;
            outline: 0;
            font-family: inherit;
            font-size: 0.95em;
        }

        .login input[type="email"],
        .login input[type="password"] {
            background: #fff;
            border-color: #bbb;
            color: #555;
        }

        .login input[type="email"]:focus,
        .login input[type="password"]:focus {
            border-color: #888;
        }

        .login input[type="submit"] {
            background: #28d;
            border-color: transparent;
            color: #fff;
            cursor: pointer;
        }

        .login input[type="submit"]:hover {
            background: #17c;
        }

        .login input[type="submit"]:focus {
            border-color: #05a;
        }

        #login_Message {
            text-align: center
        }
    </style>
</head>
<body>
<div class="login">
    <div class="login-triangle"></div>

    <h2 class="login-header">Log in</h2>

    <form class="login-container" id="login_form" autocomplete="off">
        {% csrf_token %}
        <p><input type="email" placeholder="Email" name="email"></p>
        <p><input type="password" placeholder="Password" name="password"></p>
        <p><input type="submit" value="Log in" id="login_submit"></p>
        <span id="login_Message"></span>
    </form>
</div>
<script>
    $("#login_submit").click(function (ev) {
        ev.preventDefault();
        $.ajax({
            type: "POST",
            url: "{% url 'Client:Login_Form_Ajax' %}",
            data: $('#login_form').serialize(),
            success: function (data) {
                if (data.msg !== "Empty") {
                    if (data.msg === "ContextError") {
                        $("#login_Message").html("<p>" + "Please Enter Data Correctly" + "</p>");
                    } else {
                        if (data.msg === "Done") {
                            $("#login_Message").html("<p>" + "Login Successfully Completed" + "</p>");
                            window.location = data.url;
                        }
                    }
                } else {
                    $("#login_Message").html("<p>" + "Please Enter All Data" + "</p>");
                }
            }
        });
        return false;
    });
</script>
</body>
</html>


templates/Client/settings.html
{% extends 'master.html' %}
{% load staticfiles %}
{% block meta %}
    <meta property="change_password" content="{% url 'Client:Change_Password_Ajax' %}">
    <meta property="change_email" content="{% url 'Client:Change_Email_Ajax' %}">
    <meta property="save_settings" content="{% url 'Client:Save_Settings_Ajax' %}">
{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/sweetalert2.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/settings.css' %}">
{% endblock %}
{% block body %}
    <div class="container">
        {% if client.is_active %}
            <div id="parent_loader">
                <div class="loader"></div>
            </div>

            <div class="col-md-2">
                <div class="list-type3">
                    <ul style="list-style-type:none">
                        <li><a data-id="1" class="active_li">إعدادات الحساب</a></li>
                        <li><a data-id="2">البريد الإلكتروني</a></li>
                        <li><a data-id="3">كلمة المرور</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-10 settings_div div_1 active">
                <form id="Save_Settings_Form" autocomplete="off">
                    {% csrf_token %}
                    <div class="wrap">
                        <div class="parent_mat-div col-md-6">
                            <div class="mat-div">
                                <label for="name1" class="mat-label">الاسم الأول</label>
                                <input class="mat-input" id="name1" name="name1" value="{{ client.first_name }}">
                            </div>
                        </div>
                        <div class="parent_mat-div col-md-6">
                            <div class="mat-div">
                                <label for="name2" class="mat-label">اسم الأب</label>
                                <input class="mat-input" id="name2" name="name2" value="{{ client.father_name }}">
                            </div>
                        </div>
                        <div class="parent_mat-div col-md-6">
                            <div class="mat-div">
                                <label for="name3" class="mat-label">اسم الجد</label>
                                <input class="mat-input" id="name3" name="name3" value="{{ client.grand_name }}">
                            </div>
                        </div>
                        <div class="parent_mat-div col-md-6">
                            <div class="mat-div">
                                <label for="name4" class="mat-label">اسم العائلة</label>
                                <input class="mat-input" id="name4" name="name4" value="{{ client.last_name }}">
                            </div>
                        </div>
                        <div class="parent_mat-div col-md-6">
                            <div class="mat-div">
                                <label for="phone" class="mat-label">الهاتف المحمول</label>
                                <input class="mat-input" id="phone" name="phone" value="{{ client.mobile }}">
                            </div>
                        </div>
                        <div class="parent_mat-div col-md-6">
                            <div class="mat-div">
                                <label for="id" class="mat-label">رقم الهوية</label>
                                <input class="mat-input" id="id" name="id_client" value="{{ client.identity }}">
                            </div>
                        </div>
                        <div class="parent_mat-div col-md-6">
                            <div class="mat_div_gender">
                                <div class="select-wrapper">
                                    <span class="mat_label">الفئة</span>
                                    <select class="form-control show-tick" data-size="4" name="category">
                                        <option disabled>قم بإختيار الفئة المناسبة لك</option>
                                        {% if category_all %}
                                            {% for category in category_all %}
                                                <option value="{{ category.identity }}"
                                                        {% if client.category.id == category.id %}
                                                        selected {% endif %}>{{ category.title }}</option>
                                            {% endfor %}
                                        {% endif %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="parent_mat-div col-md-6">
                            <div class="mat_div_gender">
                                <span class="mat_label">الجنس</span>
                                <div class="select-wrapper">
                                    <select class="form-control show-tick" data-size="4" name="gender">
                                        <option disabled>حدد الجنس</option>
                                        <option value="1" {% if client.gender == "1" %}selected{% endif %}>ذكر</option>
                                        <option value="2" {% if client.gender == "2" %}selected{% endif %}>أنثى</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <button id="Save_Settings_Submit">حفظ الإعدادات</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-md-10 settings_div div_2">
                <form id="Change_Email_Form" autocomplete="off">
                    {% csrf_token %}
                    <div class="col-md-12">
                        <div class="parent_mat-div col-md-6 col-md-offset-3">
                            <div class="mat-div">
                                <label for="email" class="mat-label">البريد الإلكتروني الحالي</label>
                                <input style="direction: ltr;" class="mat-input" id="email" name="email"
                                       value="{{ client.email }}" readonly>
                            </div>
                        </div>
                        <div class="parent_mat-div col-md-6 col-md-offset-3">
                            <div class="mat-div">
                                <label for="new_email" class="mat-label"> البريد الإلكتروني الجديد</label>
                                <input style="direction: ltr;" class="mat-input" id="new_email" name="new_email"
                                       value="">
                            </div>
                        </div>
                        <div class="notification col-md-6 col-md-offset-3 alert alert-info">
                            <strong>ملاحظة</strong>
                            <span style="padding-right: 5px">سيتم إرسال رمز تحقق جديد للتحقق من صحة البريد الإلكتروني الجديد، وسيتم مطالبتك بإدراج رمز التحقق للإستفادة من حسابك فيما بعد.</span>
                        </div>
                        <div class="col-md-6 col-md-offset-3">
                            <button id="Change_Email_Submit">تغيير البريد الإلكتروني</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-md-10 settings_div div_3">
                <form id="Change_Password_Form" autocomplete="off">
                    {% csrf_token %}
                    <div class="col-md-12">
                        <div class="col-md-6 col-md-offset-3" style="height: 85px">
                            <div class="mat-div">
                                <label for="password" class="mat-label">كلمة المرور الحالية</label>
                                <input class="mat-input" id="password" name="password" value="" type="password">
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-3" style="height: 85px">
                            <div class="mat-div">
                                <label for="new_password" class="mat-label">كلمة المرور الجديدة</label>
                                <input class="mat-input" id="new_password" name="new_password" value="" type="password">
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-3" style="height: 85px">
                            <div class="mat-div">
                                <label for="re_password" class="mat-label">تأكيد كلمة المرور</label>
                                <input class="mat-input" id="re_password" name="re_password" value="" type="password">
                            </div>
                        </div>
                        <div class="notification col-md-6 col-md-offset-3 alert alert-info">
                            <strong>ملاحظة</strong>
                            <span style="padding-right: 5px">سيتم تسجيل الخروج من الحساب مباشرة ، بعد تغيير كلمة المرور؛ وعليك إدخال كلمة المرور الجديدة في عمليات تسجيل الدخول القادمة</span>
                            <p><i class="fa fa-lock"></i>&nbsp;كلمة المرور الخاصة بك تحتاج إلى :</p>
                            <ul style="list-style: none">
                                <li><i class="fa fa-check"></i> تتكون كلمة المرور على الأقل من 8 أحرف</li>
                                <li><i class="fa fa-check"></i>تحتوي على حرفين على الأقل</li>
                                <li><i class="fa fa-check"></i>تتضمن رقم أو رمز واحد على الأقل</li>
                                <li><i class="fa fa-check"></i>لا تحتوي على بريدك الإلكتروني</li>
                            </ul>
                        </div>
                        <div class="col-md-6 col-md-offset-3">
                            <button id="Change_Password_Submit">تغيير كلمة المرور</button>
                        </div>
                    </div>
                </form>
            </div>
        {% else %}
            <script src="{% static 'js/is_active.js' %}"></script>
        {% endif %}
    </div>

{% endblock %}
{% block script %}
    {% if client.is_active %}
        <script src="{% static 'js/settings.js' %}"></script>
    {% endif %}
    <script src="{% static 'js/sweetalert2.min.js' %}"></script>
{% endblock %}
{% block nice_scroll %}
{% endblock %}
{% block bootstrap-select %}
{% endblock %}