Dashboard/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from Dashboard.views import *


app_name = 'Dashboard'

urlpatterns = [
    url(r'^$', HomePage.as_view(), name='HomePage'),

    url(r'^login$', LoginDashboard.as_view(), name='login'),
    url(r'^authentication/$', CheckLoginDashboard.as_view(), name='Login_Form_Ajax'),
    url(r'^logout_user/(?P<session_user>[\w-]+)/$', LogoutDashboard.as_view(), name='logoutDashboard'),
    url(r'^questions/', include('Questions.urls')),
    url(r'^category/', include('Category.urls')),
    url(r'^events/', include('Event.urls')),
    url(r'^exams/', include('Exam.urls')),
    url(r'^users/', include('Client.Users_urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Exam/urls.py
from django.conf.urls import url
from Exam.views import *

app_name = 'Exam'

urlpatterns = [
    url(r'^$', ViewExams.as_view(), name='ViewExams'),
    url(r'^add/$', AddExam.as_view(), name='Add_Exam'),
    # url(r'^edit/$', EditExam.as_view(), name='Edit_Exam_Ajax'),
    # url(r'^remove/$', RemoveExam.as_view(), name='Remove_Exam_Ajax'),
]

PalestineHistory/urls.py
from django.conf.urls import url, include
from Questions.views import *
from django.conf import settings
from django.conf.urls.static import static
from Client.views import *
from django.contrib import admin

urlpatterns = [
    # WebSite
    url(r'^$', MainPage.as_view(), name='MainPage'),

    # Dashboard
    url(r'^dashboard/admin_django/', admin.site.urls),
    url(r'^dashboard/', include('Dashboard.urls'), name='Dashboard'),

    # Client
    url(r'^user/', include('Client.urls'), name='Client'),

    # Client
    url(r'^user/', include('Video.urls'), name='Viedo'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dashboard/models.py
from django.db import models

# Create your models here.

Dashboard/views.py
from django.shortcuts import render, HttpResponseRedirect
from Client.models import *
from django.http import JsonResponse
from django.views.generic import View
from ipware.ip import get_real_ip
from django.contrib.auth.views import logout
from django.core.urlresolvers import reverse
from django.utils import timezone


class HomePage(View):
    def get(self, request):
        if request.session.get('manage', False):
            session_user = request.session.get('manage', False)
            user_agent_oop = UserAgents.objects.filter(user=session_user).latest('id')
            if user_agent_oop.logout:
                logout(request)
                return HttpResponseRedirect(reverse('Dashboard:login'))
            context = {
                'title': 'الرئيسية',
                'logout_user': session_user,
                'admin_is_manager': request.session.get('is_manager', False),
                'session_user': session_user.split('_')[0],
            }
            return render(request, 'Dashboard/index.html', context)
        else:
            return HttpResponseRedirect(reverse('MainPage'))


class LoginDashboard(View):
    def get(self, request):
        if request.session.get('client', None):
            return HttpResponseRedirect(reverse('MainPage'))
        if request.session.get('manage', None):
            session_user = request.session.get('manage', None)
            user_agent_oop = UserAgents.objects.filter(user=session_user).latest('id')
            if not user_agent_oop.logout:
                return HttpResponseRedirect(reverse('Dashboard:HomePage'))
            else:
                logout(request)
                return HttpResponseRedirect(reverse('MainPage'))
        context = {"title": "تسجيل الدخول"}
        return render(request, 'Dashboard/login.html', context)


class LogoutDashboard(View):
    def get(self, request, session_user):
        UserAgents.objects.filter(user=session_user, logout=False).update(logout=True, end_session=timezone.now())
        logout(request)
        return HttpResponseRedirect(reverse('MainPage'))


class CheckLoginDashboard(View):
    def post(self, request):
        username = request.POST.get('username').strip()
        password = request.POST.get('password')
        if username != "" and password != "":
            if username.find('@') != -1:
                username_list = username.split("@")
                name = username_list[0]
                domain = username_list[1]
                if domain.lower() == 'django':
                    if not Manager.objects.filter(username=name).first():
                        message = 'ContextError'
                    else:
                        check_user = Manager.objects.filter(username=name).first()
                        if check_user.password == password:
                            message = 'Done'
                            request.session.set_expiry(7200)
                            request.session['manage'] = username.replace('@', '_')
                            request.session['is_manager'] = check_user.is_manager
                        else:
                            message = 'ContextError'
                else:
                    message = 'ContextError'
            else:
                message = 'ContextError'
        else:
            message = 'Empty'

        context = {'msg': message}
        if message == "ContextError":
            LoginAttempts(ip=str(get_real_ip(request)), name=username, password=password,
                          browser_family=request.user_agent.browser.family,
                          browser_version=request.user_agent.browser.version_string,
                          os_family=request.user_agent.os.family,
                          os_version=request.user_agent.os.version_string,
                          device_family=request.user_agent.device.family, manage=True).save()
        elif message == "Done":
            username = username.replace('@', '_')
            user_agents = UserAgents.objects.filter(user=username, logout=False)
            if user_agents.first():
                user_agents = user_agents.latest('id')
                UserAgents.objects.filter(pk=user_agents.id).update(logout=True, end_session=timezone.now())
            UserAgents(ip=str(get_real_ip(request)), user=username,
                       browser_family=request.user_agent.browser.family,
                       browser_version=request.user_agent.browser.version_string,
                       os_family=request.user_agent.os.family,
                       os_version=request.user_agent.os.version_string,
                       device_family=request.user_agent.device.family).save()
            context['url'] = reverse('Dashboard:HomePage')
        return JsonResponse(context)

templates/Dashboard/index.html
{% extends 'Dashboard/master.html' %}
{% load staticfiles %}
{% block title %}
    {{ title }}
{% endblock %}

{% block ActiveHome %}active
{% endblock %}

{% block body %}
الصفحة الرئيسية للموقع مفروض تكون ملانة حاجات
{% endblock %}

{% block script %}

{% endblock %}

templates/Dashboard/login.html
{% load staticfiles %}
<html>
<head>
    <title> {{ title }} </title>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <link rel="icon" href="{% static 'image/Male_User.ico' %}">
    <style>
        @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700);
        body {
            background: #456;
            font-family: 'Open Sans', sans-serif;
        }
        .login {
            width: 400px;
            margin: 16px auto;
            font-size: 16px;
        }
        .login-header,
        .login p {
            margin-top: 0;
            margin-bottom: 0;
        }
        .login-triangle {
            width: 0;
            margin-right: auto;
            margin-left: auto;
            border: 12px solid transparent;
            border-bottom-color: #28d;
        }
        .login-header {
            background: #28d;
            padding: 20px;
            font-size: 1.4em;
            font-weight: normal;
            text-align: center;
            text-transform: uppercase;
            color: #fff;
        }
        .login-container {
            background: #ebebeb;
            padding: 12px;
        }
        .login p {
            padding: 12px;
        }
        .login input {
            box-sizing: border-box;
            display: block;
            width: 100%;
            border-width: 1px;
            border-style: solid;
            padding: 16px;
            outline: 0;
            font-family: inherit;
            font-size: 0.95em;
        }
        .login input[type="email"],
        .login input[type="password"] {
            background: #fff;
            border-color: #bbb;
            color: #555;
        }
        .login input[type="email"]:focus,
        .login input[type="password"]:focus {
            border-color: #888;
        }
        .login input[type="submit"] {
            background: #28d;
            border-color: transparent;
            color: #fff;
            cursor: pointer;
        }
        .login input[type="submit"]:hover {
            background: #17c;
        }
        .login input[type="submit"]:focus {
            border-color: #05a;
        }
        #login_Message {
            text-align: center
        }
    </style>
</head>
<body>
<div class="login">
    <div class="login-triangle"></div>

    <h2 class="login-header">Log in</h2>

    <form class="login-container" id="login_form" autocomplete="off">
        {% csrf_token %}
        <p><input type="email" placeholder="Email" name="username"></p>
        <p><input type="password" placeholder="Password" name="password"></p>
        <p><input type="submit" value="Log in" id="login_submit"></p>
        <span id="login_Message"></span>
    </form>
</div>
<script>
    $("#login_submit").click(function (ev) {
        ev.preventDefault();
        $.ajax({
            type: "POST",
            url: "{% url 'Dashboard:Login_Form_Ajax' %}",
            data: $('#login_form').serialize(),
            success: function (data) {
                if (data.msg !== "Empty") {
                    if (data.msg === "ContextError") {
                        $("#login_Message").html("<p>" + "Please Enter Data Correctly" + "</p>");
                    } else {
                        if (data.msg === "Done") {
                            $("#login_Message").html("<p>" + "Login Successfully Completed" + "</p>");
                            window.location = data.url;
                        }
                    }
                } else {
                    $("#login_Message").html("<p>" + "Please Enter All Data" + "</p>");
                }
            }
        });
        return false;
    });
</script>
</body>
</html>

templates/Dashboard/master.html
{% load staticfiles %}
<!DOCTYPE html>
<html dir="rtl">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'image/dashboard_icon.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/datedropper.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/date.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block style %}
    {% endblock %}
</head>
<body class="nice padding padding_top_manger">
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="manger container-fluid">
        <span>{{ session_user }}</span>
        <a href="{% url 'Dashboard:logoutDashboard' logout_user %}">تسجيل الخروج</a>
    </div>
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="">الشعار</a>
        </div>
        <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="">المسابقة</a></li>
                <li><a href="">التسجيل</a></li>
                <li><a href="">الإدارة</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="fixed-menu manger_height">
    <span class="fixed-menu-show"><i class="fa fa-bars"></i></span>
    <ul>
        <li class="{% block ActiveHome %}{% endblock %}"><a href="{% url "Dashboard:HomePage" %}"><i
                class="fa fa-home"></i>&nbsp;<span>الرئيسية</span></a>
        </li>
        <li><a class="collapse_fixed" data-toggle="collapse" href="#collapse_client" aria-expanded="false"
               aria-controls="collapseExample"><i class="fa fa-plus"></i>&nbsp;<span>المستخدمين</span></a></li>

        <ul class="collapse" id="collapse_client">
            <li class="{% block ActiveUsers %}{% endblock %}"><a href="{% url 'Dashboard:Users:ViewUsers' %}"><i
                    class="fas fa-users"></i>&nbsp;<span>عرض المستخدمين</span></a>
            </li>
            <li><a href="{% url 'Dashboard:Users:AddUser' %}"><i class="fas fa-user-plus"></i>&nbsp;<span>أضف مستخدم جديد</span></a>
            </li>
        </ul>

        <li><a class="collapse_fixed" data-toggle="collapse" href="#collapse_category" aria-expanded="false"
               aria-controls="collapseExample"><i class="fa fa-plus"></i>&nbsp;<span>الفئات</span></a></li>

        <ul class="collapse" id="collapse_category">
            <li class="{% block ActiveCategory %}{% endblock %}"><a
                    href="{% url 'Dashboard:Category:ViewCategories' %}"><i
                    class="fa fa-tags"></i>&nbsp;<span>عرض الفئات</span></a>
            </li>
            <li><a href="{% url 'Dashboard:Category:Add_Category' %}"><i class="fa fa-plus-circle"></i>&nbsp;<span>أضف فئة جديدة</span></a>
            </li>
        </ul>

        <li><a class="collapse_fixed" data-toggle="collapse" href="#collapse_fixed" aria-expanded="false"
               aria-controls="collapseExample"><i class="fa fa-plus"></i>&nbsp;<span>الاختبارات</span></a></li>
        <ul class="collapse" id="collapse_fixed">
            <li class="{% block ActiveExam %}{% endblock %}"><a href="{% url 'Dashboard:Exam:ViewExams' %}">
                <i class="fa fa-pencil-alt"></i>&nbsp;<span>عرض الاختبارت</span></a>
            </li>
            <li><a href="{% url 'Dashboard:Exam:Add_Exam' %}"><i class="fa fa-plus-circle"></i>&nbsp;<span>أضف إختبار جديد</span></a>
            </li>
        </ul>

        <li><a class="collapse_fixed" data-toggle="collapse" href="#collapse_fixed-1" aria-expanded="false"
               aria-controls="collapseExample"><i class="fa fa-plus"></i>&nbsp;<span>الأحداث</span></a></li>
        <ul class="collapse" id="collapse_fixed-1">
            <li class="{% block ActiveEvent %}{% endblock %}"><a href="{% url 'Dashboard:Event:ViewEvent' %}"><i
                    class="fa fa-globe"></i>&nbsp;<span>كل الأحداث</span></a>
            </li>
            <li class="{% block ActiveAddEvent %}{% endblock %}"><a href="{% url 'Dashboard:Event:addeventshow' %}"><i
                    class="fa fa-plus-circle"></i>&nbsp;<span>إضافة حدث</span></a>
            </li>
        </ul>

        <li><a class="collapse_fixed" data-toggle="collapse" href="#collapse_fixed-2" aria-expanded="false"
               aria-controls="collapseExample"><i class="fa fa-plus"></i>&nbsp;<span>بنك الأسئلة</span></a></li>
        <ul class="collapse" id="collapse_fixed-2">
            <li class="{% block ActiveQuestion %}{% endblock %}">
                <a href="{% url 'Dashboard:Questions:ViewQuestions' %}">
                    <i class="fa fa-question-circle"></i>&nbsp;<span>عرض الأسئلة</span></a></li>
            <li class="{% block ActiveAddQuestion %}{% endblock %}">
                <a href="{% url 'Dashboard:Questions:UploadFiles' %}">
                    <i class="fa fa-plus-circle"></i>&nbsp;<span>إضافة أسئلة</span></a></li>
        </ul>
    </ul>
</div>

<div class="container-fluid">
    <div id="view_title_page">
        <span id="dashboard_span">لوحة التحكم</span>
        <span id="title_span">{{ title }}</span>
    </div>
    {% block body %}
    {% endblock %}
</div>


<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/datedropper.min.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>